version: '2.1'

services:

  cxbox-code-samples-nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates/:/etc/nginx/templates/
    environment:
      CXBOX_APP_1: 'cxbox-code-samples-test:8080'
      CXBOX_APP_2: 'cxbox-code-samples-test:8080'
      KEYCLOAK_1: 'cxbox-code-samples-keycloak:9080'
    ports:
      - "81:80"
      - "441:443"
    restart: always
    depends_on:
      - cxbox-code-samples-test

  cxbox-code-samples-test:
    build: ./
    environment:
      FRONTEND_AUTH_SERVER_URL: 'http://code-samples.cxbox.org/auth'
      BACKEND_AUTH_SERVER_URL: 'http://code-samples.cxbox.org/auth'
      HIBERNATE_DDL_AUTO: 'update'
      DEV_PANEL_ENABLED: 'true'
      META_DIRECTORY: 'classpath:meta'
      APP_INFO_ENV: 'SMPL'
      APP_INFO_DESCRIPTION: 'v2.0.17'
      APP_INFO_COLOR: '#4C4C4C'
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://cxbox-code-samples-postgres:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      MINIO_ACCESS_KEY: '4eb6a7db8b58994ea61b'
      MINIO_SECRET_KEY: 'prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW'
      MINIO_URL: 'http://cxbox-code-samples-minio:9000'
      MINIO_DEFAULT_BUCKETS: 'edcs3gnsadevb'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    expose:
      - 8080
    ports:
      - "127.0.0.1:5005:5005"
    restart: always
    depends_on:
      - cxbox-code-samples-postgres
      - cxbox-code-samples-keycloak
      - cxbox-code-samples-minio

  cxbox-code-samples-keycloak:
    image: quay.io/keycloak/keycloak:26.4
    environment:
      KC_DB: dev-file
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 9080
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY_HEADERS: "xforwarded"
      KC_LOG_LEVEL: INFO
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      COMMENT: "If you get error `HTTPS required` on MacOS. FIX: In Docker Desktop network configuration: Settings → Resources → Network → Port binding behavior  set to: 'Localhost by default' (https://github.com/quarkusio/quarkus/discussions/48905)"
      KC_BOOTSTRAP_ADMIN_USERNAME: cxbox_admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${CXBOX_DEMO_KEYCLOAK_PASSWORD:-ASfj123214LASJhFLASldkasF3LhDGASF}
    command: start-dev --import-realm --features=scripts
    volumes:
      - ./docker/keycloak-config:/opt/keycloak/data/import/
    ports:
      - "127.0.0.1:9080:9080"
      - "127.0.0.1:9443:9443"
  cxbox-code-samples-postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    command: postgres -c 'max_connections=200'

  cxbox-code-samples-minio:
    image: bitnamilegacy/minio:2022.2.12
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: "4eb6a7db8b58994ea61b"
      MINIO_ROOT_PASSWORD: "prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW"
      MINIO_DEFAULT_BUCKETS: "edcs3gnsadevb"

