version: '2.1'

services:

  cxbox-code-samples-nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates/:/etc/nginx/templates/
    environment:
      CXBOX_APP_1: 'cxbox-code-samples-node-1:8080'
      CXBOX_APP_2: 'cxbox-code-samples-node-2:8080'
      KEYCLOAK_1: 'cxbox-code-samples-keycloak:9080'
    ports:
      - "81:80"
      - "441:443"
    restart: always
    depends_on:
      - cxbox-code-samples-node-1
      - cxbox-code-samples-node-2

  cxbox-code-samples-node-1:
    image: 'cxbox/cxbox-code-samples:latest'
    environment:
      FRONTEND_AUTH_SERVER_URL: 'http://code-samples.cxbox.org/auth/'
      BACKEND_AUTH_SERVER_URL: 'http://code-samples.cxbox.org/auth/'
      HIBERNATE_DDL_AUTO: 'none'
      DEV_PANEL_ENABLED: 'true'
      META_DIRECTORY: 'classpath:meta'
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://cxbox_postgres:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      MINIO_ACCESS_KEY: '4eb6a7db8b58994ea61b'
      MINIO_SECRET_KEY: 'prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW'
      MINIO_URL: 'http://cxbox_minio:9000'
      MINIO_DEFAULT_BUCKETS: 'edcs3gnsadevb'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n'
    expose:
      - 8080
    restart: always
    depends_on:
      - cxbox-code-samples-postgres

  cxbox-code-samples-node-2:
    image: 'cxbox/cxbox-code-samples:latest'
    environment:
      FRONTEND_AUTH_SERVER_URL: 'http://code-samples.cxbox.org/auth/'
      BACKEND_AUTH_SERVER_URL: 'http://code-samples.cxbox.org/auth/'
      HIBERNATE_DDL_AUTO: 'none'
      DEV_PANEL_ENABLED: 'true'
      META_DIRECTORY: 'classpath:meta'
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://cxbox_postgres:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      MINIO_ACCESS_KEY: '4eb6a7db8b58994ea61b'
      MINIO_SECRET_KEY: 'prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW'
      MINIO_URL: 'http://cxbox_minio:9000'
      MINIO_DEFAULT_BUCKETS: 'edcs3gnsadevb'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n'
    expose:
      - 8080
    restart: always
    depends_on:
      - cxbox-code-samples-postgres

  cxbox-code-samples-keycloak:
    image: jboss/keycloak:12.0.4
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled'
      ]
    volumes:
      - ./docker/keycloak-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${CXBOX_DEMO_KEYCLOAK_PASSWORD:-ASfj123214LASJhFLASldkasF3LhDGASF}
      - DB_VENDOR=h2
    expose:
      - 9080

  cxbox-code-samples-postgres:
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  cxbox-code-samples-minio:
    image: bitnami/minio:2022.2.12
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: "4eb6a7db8b58994ea61b"
      MINIO_ROOT_PASSWORD: "prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW"
      MINIO_DEFAULT_BUCKETS: "edcs3gnsadevb"

