app:
  auth-basic:
    enabled: ${AUTH_BASIC_ENABLED:false}
  oidc:
    realm: cxbox
    auth-server-url: ${FRONTEND_AUTH_SERVER_URL:http://localhost:9080/auth}
    ssl-require: none
    resource: cxbox-oidc-client
    public-client: true
    cors: true
  stomp:
    stomp-post: ${STOMP_PORT:61613}
    broker-type: ${BROKER_TYPE:simple}
  activemq:
    password: ${ACTIVEMQ_ADMIN_PASSWORD:admin}
    user: ${ACTIVEMQ_ADMIN_LOGIN:admin}
    broker-url: tcp://${ACTIVEMQ_HOST:localhost}:${ACTIVEMQ_PORT:61616}
    host: ${ACTIVEMQ_HOST:}
    port: ${ACTIVEMQ_PORT:61616}
  integrations:
    # exits in demo.cxbox.org, but NOT in code-samples.cxbox.org
    #lov-server-url: ${LOV_SERVER_URL:http://localhost:8080/rest/api/v1/lov}
    # exits ONLY in code-samples.cxbox.org
    create-microservices-data-server-url: ${CREATE_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3910}
    existing-microservices-data-server-url: ${EXISTING_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3900}
    get-started-microservices-data-server-url: ${GET_STARTED_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity4001}
    next-and-previous-microservices-data-server-url: ${NEXT_PAGE_1_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity4002}
    suggestion-microservices-data-server-url: ${SUGGESTION_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3081}
    data-server-url: ${DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3137}
    dictionary_data-server-url: ${DICTIONRY_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/dictionary}
cxbox:
  bean:
    multipart-resolver:
      enabled: false
  meta:
    dev-panel-enabled: ${DEV_PANEL_ENABLED:true}
    directory: ${META_DIRECTORY:file:./src} #value ${META_DIRECTORY:file:./src/main/resources/meta} from demo.cxbox.org changed due to .json files are placed in java packages in code samples
    view-allowed-roles-enabled: true
    widget-action-groups-enabled: true
    widget-action-groups-compact: true
    bc-default-page-limit: 5
  widget:
    fields:
      include-packages: org.cxbox.meta, org.demo.conf.cxbox
      sort-enabled-default: false
      filter-by-range-enabled-default: true
  api:
    path: /api/v1
  ui:
    path: /ui
    multi-role-enabled: false
    drill-down-tooltip: newAndCopy

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true

spring:
  mail:
    host: ${MAIL_HOST:false}  #  For local development empty - e.g. turned off. on server fill this prop
    port: 587
    username: ${MAIL_USER:}  #  For local development, you can use your own data, or use those prepared
    password: ${MAIL_PASSWORD:}  #  from the CXBOX-1 ticket or the secrets of the EMAIL_DATA repository
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  websocket:
    endpointToConnect: ${WEBSOCKET_ENDPOINT:/websocketnotification}
    prefix: /user
    urlPath: /queue/websocket.reply
  datasource:
    name: primaryDS
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    drop-first: true
    contexts: local
  cache:
    type: SIMPLE
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
        hbm2ddl:
          auto: ${HIBERNATE_DDL_AUTO:update} #value ${HIBERNATE_DDL_AUTO:none} from demo.cxbox.org changed due code samples use tables auto creation by hibernate which is enough for demonstration purposes
    org:
      cxbox:
        dictionary:
          enable_types_contributor: true
    hibernate:
      naming:
        physical-strategy: org.cxbox.model.core.hbn.ImprovedPhysicalNamingStrategy

  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FRONTEND_AUTH_SERVER_URL:http://localhost:9080/auth}/realms/cxbox
          jwk-set-uri: ${BACKEND_AUTH_SERVER_URL:http://localhost:9080/auth}/realms/cxbox/protocol/openid-connect/certs

token:
  converter:
    principal-attribute: preferred_username
    resource-id: cxbox-oidc-client

minio:
  access:
    name: ${MINIO_ACCESS_KEY:4eb6a7db8b58994ea61b}
    secret: ${MINIO_SECRET_KEY:prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW}
  url: ${MINIO_URL:http://localhost:9000}
  bucket:
    name: ${MINIO_DEFAULT_BUCKETS:edcs3gnsadevb}

management:
  health:
    jms:
      enabled: false
  endpoint:
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: 'metrics'

# exits in demo.cxbox.org, but NOT in code-samples.cxbox.org
#dadata:
#  client:
#    token: ${DADATA_API_KEY:885218b4321600b90d4161c85bc11766cd6810c1}
#    base-url: ${DADATA_URL:https://suggestions.dadata.ru/suggestions/api/4_1/rs/}
#
#org:
#  jobrunr:
#    background-job-server:
#      enabled: true
#    dashboard:
#      enabled: false


# exits ONLY in code-samples.cxbox.org
logbook:
  include:
    - /**
  exclude:
    - /ui/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/v1/data/**
    - /api/v1/row-meta/**
    - /api/v1/count/**
  write:
    max-body-size: 5000
  format:
    style: http

document:
  force-active-enabled: ${FORCE_ACTIVE_ENABLED:true}



