app:
  ui-path: /ui
  auth-basic:
    enabled: ${AUTH_BASIC_ENABLED:false}
  oidc:
    realm: cxbox
    auth-server-url: ${FRONTEND_AUTH_SERVER_URL:http://localhost:9080/auth}
    ssl-require: none
    resource: cxbox-oidc-client
    public-client: true
    cors: true
  integrations:
    reate-microservices-data-server-url: ${CREATE_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3910}
    existing-microservices-data-server-url: ${EXISTING_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3900}
    get-started-microservices-data-server-url: ${GET_STARTED_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity4001}
    next-and-previous-microservices-data-server-url: ${NEXT_PAGE_1_MS_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity4002}
    suggestion-microservices-data-server-url: ${SUGGESTION_DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3081}
    data-server-url: ${DATA_SERVER_URL:http://localhost:8080/rest/api/microservices/v1/myentity3137}
cxbox:
  bean:
    multipart-resolver:
      enabled: false
  meta:
    dev-panel-enabled: ${DEV_PANEL_ENABLED:true}
    directory: ${META_DIRECTORY:file:./src}
    view-allowed-roles-enabled: true
  widget:
    fields:
      include-packages: org.cxbox.meta, org.demo.conf.cxbox
      filter-by-range-enabled-default: false
  api:
    path: /api/v1
    use-servlet-context-path: false
  ui:
    path: /ui
    use-servlet-context-path: false

server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    name: primaryDS
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    drop-first: true
    contexts: local
  cache:
    type: SIMPLE
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
        hbm2ddl:
          auto: update
    hibernate:
      naming:
        physical-strategy: org.cxbox.model.core.hbn.ImprovedPhysicalNamingStrategy
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FRONTEND_AUTH_SERVER_URL:http://localhost:9080/auth}/realms/cxbox
          jwk-set-uri: ${BACKEND_AUTH_SERVER_URL:http://localhost:9080/auth}/realms/cxbox/protocol/openid-connect/certs

token:
  converter:
    principal-attribute: preferred_username
    resource-id: cxbox-oidc-client

springdoc:
  packages-to-scan: org.demo

minio:
  access:
    name: ${MINIO_ACCESS_KEY:4eb6a7db8b58994ea61b}
    secret: ${MINIO_SECRET_KEY:prCv8t9LGRH18FB5pLr5jqDZ/dixZkb9cFajueGW}
  url: ${MINIO_URL:http://localhost:9000}
  bucket:
    name: ${MINIO_DEFAULT_BUCKETS:edcs3gnsadevb}

document:
  force-active-enabled: ${FORCE_ACTIVE_ENABLED:true}

logbook:
  include:
    - /**
  exclude:
    - /ui/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/v1/data/**
    - /api/v1/row-meta/**
    - /api/v1/count/**
  write:
    max-body-size: 5000
  format:
    style: http

decorator:
  datasource:
    datasource-proxy:
      query:
        enable-logging: true
        log-level: DEBUG
      multiline: true