name: Build project

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-main-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK '17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: "maven"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: "yarn"
          cache-dependency-path: ui
      - name: Build with Maven
        run: mvn clean install -U -PUI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cxbox-code-samples:latest
      - name: prepare - stop all containers from previous deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 188.124.37.74
          username: ${{ secrets.CXBOX_DEMO_SSH_USER }}
          password: ${{ secrets.CXBOX_DEMO_SSH_PASSWORD }}
          port: 22
          script: |
            sudo mkdir /home/cxbox/code-samples || true
            sudo chmod -R 777 /home/cxbox/code-samples || true
            cd /home/cxbox/code-samples
            sudo docker ps
            sudo docker compose -f docker-compose-prod.yml rm -svfa || true
            sudo docker system prune --force
            sudo docker volume prune --force
            sudo docker image prune -a --force
            sudo docker ps
      - name: prepare - copy files from new release and delete old files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 188.124.37.74
          username:  ${{ secrets.CXBOX_DEMO_SSH_USER }}
          password: ${{ secrets.CXBOX_DEMO_SSH_PASSWORD }}
          port: 22
          source: "docker,docker-compose-prod.yml"
          target: /home/cxbox/code-samples
          rm: true
      - name: start
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 188.124.37.74
          username: ${{ secrets.CXBOX_DEMO_SSH_USER }}
          password: ${{ secrets.CXBOX_DEMO_SSH_PASSWORD }}
          port: 22
          script: |
            sudo chmod -R 777 /home/cxbox/code-samples || true
            cd /home/cxbox/code-samples
            sudo docker compose -f docker-compose-prod.yml up -d --wait -t 60
            docker ps
