name: QA project

on:
  push:
    branches:
    - CXBOX-725
  pull_request:
    branches:
    - CXBOX-725
  workflow_dispatch:

env:
  APP_URL: http://localhost:81/ui/#/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Build docker image
        run: docker compose build

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cashe: "yarn"
          cache-dependency-path: ui

      - name: Load target
        run: mvn clean install -U -PUI

      - name: Stop and remove containers, networks
        run: sudo docker compose -f docker-compose-test.yml down --remove-orphans

      - name: Remove unused data
        run: sudo docker system prune -a --volumes -f
        #Change to docker container prune -f && docker network prune -f ?

      - name: List Docker images
        run: docker images

      - name: Build docker-compose
        run: sudo docker compose -f docker-compose-test.yml build

      - name: Set permissions for ./docker
        run: sudo chmod -R 777 ./docker

      - name: Start docker-compose run
        run: sudo docker compose -f docker-compose-test.yml up -d

      - name: Run tests
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.Info.InputOnInfoTest test

      - name: List screenshots directory
        if: always()
        run: ls -la build/reports/tests/

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: build/reports/tests/

      - name: Stop and remove Docker compose
        if: always()
        run:  sudo docker compose -f docker-compose-test.yml down

      - name: Upload allure results
        if: always() && github.event_name == 'pull_request'  # Only for pull_request
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always() && github.event_name == 'pull_request'  # Only for pull_request
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always() && github.event_name == 'pull_request'  # Only for pull_request
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          allure_reports: allure-report
          keep_reports: 20

      - name: Prepare someone directory
        if: always() && github.event_name == 'pull_request'  # Only for pull_request
        run: |
          mkdir -p gh-pages/someone
          cp -r allure-report/* gh-pages/someone/

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always() && github.event_name == 'pull_request'  # Only for pull_request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always() && github.event_name == 'pull_request'  # Only for pull_request
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}