name: Run tests by button

on: 
  workflow_dispatch:
   inputs:
     choice-test:
       type: choice
       description: Package
       options:
       - All tests
       - Package, class or test
     test-path:
       description: include PATH
       type: string
       required: false
     video_tags:
       description: "Record failed video"
       required: false
       type: boolean
     log_tags:
       description: "Logging network"
       required: false
       default: true
       type: boolean

env:
  APP_URL: http://code-samples.cxbox.org/ui/#/
  CXBOX_RECORDER:  ${{ github.event.inputs.video_tags == 'true' && 'true' || 'false' }}
  CXBOX_LOGGER:  ${{ github.event.inputs.log_tags == 'true' && 'true' || 'false' }}
    
jobs:
  build_main:
    if: ${{inputs.choice-test == 'All tests' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Create reports directory
        run: mkdir -p build/reports/tests/
        
      - name: Run default tests
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.Form.**,application.Samples.Info.** test

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          allure_reports: allure-report
          keep_reports: 20

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Generate and add report URL to Job Summary 
        run: |
          REPORT_URL="https://cx-box.github.io/cxbox-code-samples/"
          echo "Report URL: $REPORT_URL"
          echo "::notice::Report URL: $REPORT_URL"
          echo "### Report URL" >> $GITHUB_STEP_SUMMARY
          echo "The report is available at: $REPORT_URL" >> $GITHUB_STEP_SUMMARY   

  build_manual:
    if: ${{inputs.choice-test == 'Package, class or test' || github.ref != 'refs/heads/main'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Create reports directory
        run: mkdir -p build/reports/tests/

      - name: Run some kind of test 
        if: ${{inputs.choice-test == 'Package, class or test'}}
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.${{github.event.inputs.test-path}} test

      - name: Run default tests
        if: ${{inputs.choice-test == 'All tests' }}
        run: |
          mvn --batch-mode -DrunTests=true -Dtest=application.Samples.Form.**,application.Samples.Info.** test    
      
      - name: Create side-tests directory
        if: always()
        run: mkdir -p gh-pages/side-tests  

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results 

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_report: gh-pages/side-tests/${{ github.run_number }}/allure-report
          keep_reports: 20
          
      - name: List report directory
        run: ls -R gh-pages/side-tests/${{ github.run_number }}/allure-report  
        
      - name: Prepare files for deployment
        if: always()
        run: |
          mkdir -p deploy/side-tests/${{ github.run_number }}
          cp -r gh-pages/side-tests/${{ github.run_number }}/allure-report/* deploy/side-tests/${{ github.run_number }}/  
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: deploy/side-tests
          destination_dir: side-tests
          keep_files: true

      - name: Generate and add report URL to Job Summary 
        if: always()
        run: |
          REPORT_URL="https://cx-box.github.io/cxbox-code-samples/side-tests/${{ github.run_number }}"
          echo "Report URL: $REPORT_URL"
          echo "::notice::Report URL: $REPORT_URL"
          echo "### Report URL" >> $GITHUB_STEP_SUMMARY
          echo "The report is available at: $REPORT_URL" >> $GITHUB_STEP_SUMMARY
          
        
        
