name: QA

on:
  push:
    branches:
      - main
  pull_request:
     branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  APP_URL: http://localhost:81/ui/#/
  CXBOX_LOGGER:  true

jobs:
  build-qa-pr-and-check-autotests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17','21']
    name: QA tests Java ${{ matrix.java }}
    env:
      COMPOSE_PROJECT_NAME: pr_${{ github.run_id }}_${{ matrix.java }}
    steps:
      # -------------------------
      # BASE
      # -------------------------
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: "maven"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: "yarn"
          cache-dependency-path: ui/yarn.lock
      # -------------------------
      # BUILD BACK + FRONT
      # -------------------------
      - name: Build backend + UI
        run: mvn clean install -U -PUI

      # -------------------------
      # START DOCKER
      # -------------------------

      - name: Start isolated docker environment
        run: |
          sudo chmod -R 777 ./docker
          sudo docker images
          docker compose -f docker-compose-test.yml up -d

      # -------------------------
      # TESTS
      # -------------------------
      - name: Run Tests
        id: run_tests
        continue-on-error: true
        run: |
          mvn --batch-mode \
            -DrunTests=true \
            -Dsurefire.parallel=classes \
            -Dsurefire.forkCount=3 \
            -Dsurefire.threadCount=1 \
            -Dsurefire.reuseForks=true \
            -Dtest=application.Samples.Form.**\
            test

      - name: Save test result
        if: always()
        run: |
          echo "${{ matrix.java }}=${{ steps.run_tests.outcome }}" > test-result-${{ matrix.java }}.txt

      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{ matrix.java }}
          path: test-result-${{ matrix.java }}.txt

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          repository: CX-Box/cxbox-code-samples-allure
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.CODE_SAMPLES_ALLURE }}

      - name: Prepare Allure history
        if: always()
        run: |
          mkdir -p target/allure-results
          mkdir -p gh-pages/pull_request/java-${{ matrix.java }}/last-history
          mkdir -p gh-pages/pull_request/java-${{ matrix.java }}/history
      - name: Check allure results
        if: always()
        run: |
          ls -la target/allure-results
          find target/allure-results -type f | head
      - name: Test here and host elsewhere
        uses: simple-elf/allure-report-action@v1.15
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages/pull_request/java-${{ matrix.java }}
          allure_report: allure-report/java-${{ matrix.java }}
          allure_history: allure-history/java-${{ matrix.java }}
          github_repo: CX-Box/cxbox-code-samples-allure
          github_repo_owner: CX-Box
          report_url: https://cx-box.github.io/cxbox-code-samples-allure/pull_request/java-${{ matrix.java }}
          keep_reports: 20
  publish-summary:
    name: Publish Report Links
    runs-on: ubuntu-latest
    needs: [build-qa-pr-and-check-autotests]
    if: always()

    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          pattern: test-result-*
          merge-multiple: true
      - name: Prepare PR comment
        if: always()
        id: comment
        run: |
          JAVA17=$(cat test-result-17.txt)
          JAVA21=$(cat test-result-21.txt)
          
          if [ "$JAVA17" = "success" ]; then
            echo "java17=☕ Java 17 ✅ Passed" >> $GITHUB_OUTPUT
          else
            echo "java17=☕ Java 17 ❌ Failed" >> $GITHUB_OUTPUT
          fi
          
          if [ "$JAVA21" = "success" ]; then
            echo "java21=☕ Java 21 ✅ Passed" >> $GITHUB_OUTPUT
          else
            echo "java21=☕ Java 21 ❌ Failed" >> $GITHUB_OUTPUT
          fi

      - name: Comment on Pull Request
        if: always()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.CODE_SAMPLES_ALLURE }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### QA autotests result

            ${{ steps.comment.outputs.java17 }}
            https://cx-box.github.io/cxbox-code-samples-allure/pull_request/java-17/${{ github.run_number }}

            ${{ steps.comment.outputs.java21 }}
            https://cx-box.github.io/cxbox-code-samples-allure/pull_request/java-21/${{ github.run_number }}
 

      - name: Remove only created docker containers
        if: always()
        run: |
            export COMPOSE_PROJECT_NAME="${{ env.COMPOSE_PROJECT_NAME }}"
  
            echo "Stopping containers for $COMPOSE_PROJECT_NAME..."
            docker compose -f docker-compose-test.yml down --remove-orphans
  
            echo "Removing containers by label..."
            docker container prune -f --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME"
  
            echo "Removing networks by label..."
            docker network prune -f --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME"
  
            echo "Done!"
