name: QA project

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  APP_URL: http://localhost:81/ui/#/


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Check Files
        run: cd /mnt/c/git/cxbox-code-samples/docker/nginx/conf/ && ls && cat nginx.conf

      - name: Check if nginx.conf exists
        run: |
            ls -la ./docker/nginx/conf/
            cat ./docker/nginx/conf/nginx.conf
      - name: Build docker image
        run: docker compose build

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: ui

      - name: Install Yarn
        run: npm install -g yarn

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
            maven-version: '3.9.6'

      - name: Load target
        run: mvn clean install -U -PUI

      - name: Stop and remove containers, networks
        run: sudo docker compose -f docker-compose-test.yml down --remove-orphans

      - name: Remove unused data
        run: sudo docker system prune -a --volumes -f
        #Change to docker container prune -f && docker network prune -f ?

      - name: List Docker images
        run: docker images

      - name: Build docker-compose
        run: sudo docker compose -f docker-compose-test.yml build

      - name: Set permissions for ./docker
        run: sudo chmod -R 777 ./docker

      - name: Check permission
        run: stat -c "%a %n" ./docker/nginx/conf/nginx.conf

      - name: Start docker-compose run
        run: sudo docker compose -f docker-compose-test.yml up -d

      - name: Wait for application to start
        run: sudo curl --retry 15 --retry-delay 5 --retry-connrefused http://localhost:81

      - name: Run tests
        run: mvn --batch-mode --update-snapshots -DrunTests=true verify

      - name: Stop and remove Docker compose
        run:  sudo docker compose -f docker-compose-test.yml down
