name: Run tests by button

on: 
  workflow_dispatch:
   inputs:
     choice-test:
       type: choice
       description: Package
       options:
       - All tests
       - Package, class or test
     test-path:
       description: include PATH
       type: string
       required: false

env:
  APP_URL: http://code-samples.cxbox.org/ui/#/
    
jobs:
  build_main:
    if: ${{inputs.choice-test == 'All tests' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Create reports directory
        run: mkdir -p build/reports/tests/
        
      - name: Run default tests
        if: ${{inputs.choice-test == 'All tests' }} 
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.Form.**,application.Samples.Info.** test

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          allure_reports: allure-report
          keep_reports: 20

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  build_someone:
    if: ${{inputs.choice-test == 'Package, class or test' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Create reports directory
        run: mkdir -p build/reports/tests/

      - name: Run some kind of test 
        if: ${{inputs.choice-test == 'Package, class or test'}}
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.${{github.event.inputs.test-path}} test

      - name: Run default tests
        if: ${{inputs.choice-test == 'All tests' }}
        run: |
          mvn --batch-mode -DrunTests=true -Dtest=application.Samples.Form.**,application.Samples.Info.** test    

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Create side-test directory
        run: mkdir -p gh-pages/side-tests     

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_report: gh-pages/side-tests/${{ github.run_number }}/allure-report
          keep_reports: 20
          
      - name: Commit and push Allure report to gh-pages
        if: always()
        run: |
          REPORT_DIR="gh-pages/side-tests/${{ github.run_number }}"
          mkdir -p $REPORT_DIR
          cp -r target/allure-results/* $REPORT_DIR/
          cd gh-pages

          ls -dt side-tests/* | tail -n +11 | xargs rm -rf

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git status
          git commit -m "Add Allure report for run ${{ github.run_number }}"
          git push origin gh-pages
        
        
