name: Run tests by button

on: 
  workflow_dispatch:
   inputs:
     choice-test:
       type: choice
       description: Package
       options:
       - All tests
       - Package, class or test
     test-path:
       description: include PATH
       type: string
       required: false

env:
  APP_URL: http://code-samples.cxbox.org/ui/#/
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"

      - name: Create reports directory
        run: mkdir -p build/reports/tests/
        
      - name: Run default tests
        if: ${{inputs.choice-test == 'All tests' }} 
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.Form.**,application.Samples.Info.** test
            
      - name: Run some kind of test 
        if: ${{inputs.choice-test == 'Package, class or test'}}
        run: mvn --batch-mode -DrunTests=true -Dtest=application.Samples.${{github.event.inputs.test-path}} test    
        
      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          allure_reports: allure-report

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
